language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  global:
  - PATH=${PATH}:${HOME}/.cargo/bin
  matrix:
  - TRAVIS_RUST_VERSION=nightly
install:
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - pip install -r requirements.txt
script:
  - cargo test --verbose
  - cargo test --release --verbose
  - python3 -mix -v test
  - python3 -mix -v clean
matrix:
  allow_failures:
  - python: "3.7-dev"
cache:
  pip: true
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
  - $TRAVIS_BUILD_DIR/testcases

