language: python
dist: trusty
python:
- "3.5"
- "3.6"
- "3.7-dev"
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - llvm-5.0
env:
  global:
  - PATH=${PATH}:${HOME}/.cargo/bin
  matrix:
  - TRAVIS_RUST_VERSION=nightly
  - TRAVIS_RUST_VERSION=nightly-2018-06-18
install:
- curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
- pip install -r requirements.txt
script:
- cargo test --verbose
- cargo test --release --verbose
- find solutions -name '*.rs' | RUSTFLAGS="--cfg local -Z borrowck=mir -Z polonius" xargs -I {} python3 -mix -v generate {}.c
- python3 -mix -v test
- python3 -mix -v clean
after_success:
- CARGO_INCREMENTAL=0 RUSTFLAGS='-Z borrowck=mir -Z polonius -Z profile -C opt-level=0 -C no-prepopulate-passes -C link-dead-code -C overflow-checks=off -C inline-threshold=0 -C codegen-units=1' cargo test -v
- CARGO_INCREMENTAL=0 RUSTFLAGS='-Z borrowck=mir -Z polonius -Z profile -C opt-level=0 -C no-prepopulate-passes -C link-dead-code -C overflow-checks=off -C inline-threshold=0 -C codegen-units=1' python3 -mix -v test
- find target/debug/deps -name 'porus*' | grep -v gcno | grep -v gcda | xargs -I {} llvm-cov gcov -l -p {}
- find solutions -name '*.rs' | xargs -I {} llvm-cov gcov -l -p {}
- pip install requests
- python3 coveralls.py
- python3 -mix -v clean
- rm *.gcov
matrix:
  allow_failures:
  - env: TRAVIS_RUST_VERSION=nightly
  - python: "3.7-dev"
cache:
  pip: true
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
  - $TRAVIS_BUILD_DIR/testcases
