language: python
dist: trusty
python:
- "3.5"
- "3.6"
- "3.7-dev"
env:
  global:
  - PATH=${PATH}:${HOME}/.cargo/bin
  matrix:
  - TRAVIS_RUST_VERSION=nightly
install:
- curl -sSf https://sh.rustup.rs/ | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
- pip install -r requirements.txt
- CARGO_TARGET_DIR="${HOME}/.cargo/target" cargo install cargo-update || echo "cargo-update already installed"
- CARGO_TARGET_DIR="${HOME}/.cargo/target" cargo install --git git://github.com/bhuztez/cov cargo-cov || echo "cargo-cov already installed"
- CARGO_TARGET_DIR="${HOME}/.cargo/target" cargo install-update -ag
script:
- cargo test --verbose
- find solutions -name '*.rs' | RUSTFLAGS="--cfg local -Z borrowck=mir -Z polonius" xargs -I {} python3 -mix -v generate {}.c
- python3 -mix -v test
- python3 -mix -v clean
after_success:
- cargo cov clean
- COVERAGE=1 python3 -mix -v test
- cargo cov test -v
- cargo cov report --coveralls
matrix:
  allow_failures:
  - python: "3.7-dev"
cache:
  pip: true
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
  - $TRAVIS_BUILD_DIR/testcases
