[package]
name = "porus_macros"
description = "porus macros"
version = "0.0.0"
authors = ["bhuztez <bhuztez@gmail.com>"]
license = "MIT"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
proc-macro2 = "0.4.9"
quote = "0.6.4"

[dependencies.syn]
version = "0.14.5"
features = ["full"]
