[package]
name = "porus_macros"
description = "porus macros"
version = "0.0.0"
authors = ["bhuztez <bhuztez@gmail.com>"]
license = "MIT"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
proc-macro2 = "0.4.24"
quote = "0.6.10"

[dependencies.syn]
version = "0.15.23"
features = ["full"]
