[package]
name = "porus_derive"
description = "porus derive"
version = "0.0.0"
authors = ["bhuztez <bhuztez@gmail.com>"]
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "0.14.2"
proc-macro2 = "0.4.6"
quote = "0.6.3"
