[package]
name = "porus"
description = "porus library"
version = "0.0.0"
authors = ["bhuztez <bhuztez@gmail.com>"]
license = "MIT"

[dependencies]
porus_macros = { path = "../porus_macros" }
porus_derive = { path = "../porus_derive" }
